repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv
        args: [run, ruff, check, ., --fix]
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: ruff format
        entry: uv
        args: [run, ruff, format, .]
        language: system
        pass_filenames: false
        always_run: true

      - id: ty-check
        name: ty check
        entry: uv
        args: [run, ty, check, .]
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: uv
        args: [run, pytest]
        language: system
        pass_filenames: false
        always_run: true