version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv pip install --system pdoc
    - uv pip install --system .
    - pdoc src/qq_lib -d google -o $READTHEDOCS_OUTPUT/html